### ISSUE TITLE
Dependencies are incorrectly configured

### ISSUE THREAD

**Issue by alanf** [comyarzaheri/Partita#2]
Hello, I just tried out this project but ran into a couple of issues. After running `pod install`, I see the following:

```
[!] The `Partita [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods/Pods.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Partita [Release]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

Regardless of whether I delete or keep that setting, I get the following when trying to build for the simulator or a device:

<img width="259" alt="screen shot 2016-02-06 at 5 16 43 pm" src="https://cloud.githubusercontent.com/assets/154965/12870334/ff7de44a-ccf4-11e5-84ba-f91a6234a1f3.png">

**Comment by comyarzaheri** [comment]
This should be fixed now, feel free to re-open if you run into any more issues!
