### ISSUE TITLE
Cant clone this project

### ISSUE THREAD

**Issue by hungwei0331** [comyarzaheri/Partita#3]
I had been try those command below

$ git clone https://github.com/comyarzaheri/Partita.git
$ cd Partita
$ pod install
$ open .

but when I type "$pod install" it occur error like this

[!] The dependency `AMWaveTransition (~> 0.6.2)` is not used in any concrete target.
The dependency `PodsLicenseReader (~> 0.0.3)` is not used in any concrete target.
The dependency `PermissionScope (~> 1.0.2)` is not used in any concrete target.
The dependency `BubbleTransition (~> 1.0.1)` is not used in any concrete target.
The dependency `BFPaperButton (~> 2.0.18)` is not used in any concrete target.
The dependency `WMGaugeView (~> 0.0.3)` is not used in any concrete target.
The dependency `TuningFork (~> 0.1.1)` is not used in any concrete target.

I m wondering how to fix those problem,

thanks for any comment in advance

**Comment by comyarzaheri** [comment]
Hi, looks like CocoaPods 1.0 enforces stricter rules on Podfiles. I've update the Podfile for this project, so everything should work now.
