### ISSUE TITLE
build project unsuccessfully

### ISSUE THREAD

**Issue by hungwei0331** [comyarzaheri/Partita#4]
Sorry to bother you again,

After I clone the project, during build the project it occur error below

~/Partita/Partita/MainViewController.swift:30:8: No such module 'TuningFork'

And I am sure I had been Installing TuningFork (0.1.1)

Could you help me how to solve this problem , 

Thank you very much.

**Comment by comyarzaheri** [comment]
Alright, I think there was an update to CocoaPods which broke some of the assumptions I was making in the project setup. I believe it should be fixed now, try doing a fresh clone and tell me how it goes.

**Comment by hungwei0331** [comment]
Thank for your passion,
 it works well now.
